name: ci
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --config .github/lychee.toml README.md
          fail: true
